spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: false

  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}
  jackson:
    serialization:
      order-map-entries-by-keys: true